#!/bin/bash

set -euo pipefail

if ! docker version >/dev/null 2>&1; then
  echo "Starting docker daemon..."
  sudo systemctl start docker
fi

echo "Starting gitsome..."
docker run -ti --rm \
  -v "${HOME}"/.gitsomeconfig:/root/.gitsomeconfig:Z \
  -v "${HOME}"/.gitconfig:/root/.gitconfig:ro,Z \
  mariolet/gitsome
