#!/bin/bash


docker version > /dev/null 2>&1
if [ $? -ne 0 ]; then
    sudo systemctl start docker
fi

set -x

docker run -ti --rm  \
   -v ${HOME}/.gitsomeconfig:/root/.gitsomeconfig:Z  \
   -v ${HOME}/.gitconfig:/root/.gitconfig:ro,Z        \
   mariolet/gitsome
