#!/bin/bash

set -x

sudo systemctl start docker
docker run -ti --rm  \
   -v ${HOME}/.gitsomeconfig:/root/.gitsomeconfig:Z  \
   -v ${HOME}/.gitconfig:/root/.gitconfig:ro,Z        \
   mariolet/gitsome
