#!/bin/bash

kvm=$1
if [[ "${kvm}" = "kvm" ]]; then
  args="--vm-driver=kvm2"
else
  args=""
fi

set -euo pipefail

minikube start \
  --kubernetes-version v1.18.0 \
  --cpus 3 --memory 4000 \
  --v 10 "${args}"
