#!/bin/bash

kvm=$1
if [[ "${kvm}" = "kvm" ]]; then
  args="--vm-driver=kvm2"
else
  args=""
fi

set -euo pipefail

minikube start \
  --kubernetes-version v1.18.6 \
  --cpus 4 --memory 5000 \
  --v 10 "${args}"
