#!/bin/bash

version=$1
if [ -z $version ]; then
    echo "Please provide the helm version, find the latest one at: https://github.com/helm/helm/releases"
    echo "update-helm v2.14.3"
    exit 1
fi

set -x

cd /tmp

curl -LO https://storage.googleapis.com/kubernetes-helm/helm-$version-linux-amd64.tar.gz
tar -xvzf helm-$version-linux-amd64.tar.gz
mv linux-amd64/helm ~/.local/bin/
