#!/usr/bin/env bash

# Detect OS
os=$(uname)
case $os in
Darwin)
  brew install helm
  exit 0
  ;;

Linux)
  # no op
  ;;

*)
  echo "unsupported OS: ${os}"
  exit 1
  ;;
esac

version=$1
if [ -z "${version}" ]; then
  echo "Please provide the helm version, find the latest one at: https://github.com/helm/helm/releases"
  echo "update-helm v2.14.3"
  exit 1
fi

set -euo pipefail
set -x

cd /tmp

curl -LO https://get.helm.sh/helm-"${version}"-linux-amd64.tar.gz
tar -xvzf helm-"${version}"-linux-amd64.tar.gz
mv linux-amd64/helm ~/.local/bin/
