#!/bin/bash

set -euo pipefail

# shellcheck source=/dev/null
source "$(dirname "${BASH_SOURCE[0]}")"/util.sh

# find what the latest version is
get_latest_release kubernetes/minikube
echo "Downloading minikube ${version}"

# goto temp dir to download artifacts and then move it
cd /tmp || exit 1

# create this directory which is in path in linux distros
# like fedora, centos and ubuntu.
mkdir -p ~/.local/bin/
curl --silent -Lo minikube https://storage.googleapis.com/minikube/releases/"${version}"/minikube-linux-amd64 &&
  chmod +x minikube &&
  mv minikube ~/.local/bin/
echo "Downloaded successfully in ~/.local/bin/"
