[package]
name = "ssd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arboard = "3.2.1"
chrono = "0.4.31"
clap = { version = "4.4.6", features = ["cargo"] }
shellexpand = "3.1.0"
