[character]
success_symbol = '[➜](bold green) '
error_symbol   = '[✗](bold red) '

# Git specific configuration
[git_branch]
symbol = '🔀 '

[git_commit]
tag_symbol = ' 🏷 '

# Kubernetes specific configuration
[kubernetes]
disabled = false
symbol   = "☸️ "

# Azure specific configuration
[azure]
disabled = false
symbol   = '󰠅 '

# Container detection
[custom.container]
disabled = false
when     = 'test "$RUNNING_IN_CONTAINER" = "true"'
format   = '[$symbol(Container)]($style) '
symbol   = '📦 '
style    = 'bold dimmed white'
